services:
  
  php:
    container_name: php_docker
    restart: always
    build:
      context: ./
      dockerfile: ./dockerfiles/php
    volumes:
      - "./public:/var/www/html"
    ports:
      - 80:80

  mysql:
    container_name: mysql_docker
    restart: always
    build:
      context: ./
      dockerfile: ./dockerfiles/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    container_name: phpmyadmin_docker
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 7000:80

  # mailhog:
  #   container_name: mailhog_bc
  #   image: mailhog/mailhog
  #   ports:
  #     - 1025:1025 # smtp server
  #     - 8025:8025 # web ui

version: '3'